### ISSUE TITLE
Update the app's name and favicon to make it more appealing and user-friendly.

### ISSUE THREAD

**Issue by aaditya9899** [aaditya9899/mini-trello#1]
The current app name and favicon do not accurately represent the content or branding of the application.
Feel free to choose your own favicon from the net which matches the application functionality.

### Screenshots 

![h1](https://github.com/aaditya9899/mini-trello/assets/38832156/05ab283a-5fba-4800-9185-2f29cf0858f7)

**Comment by Vaishali785** [comment]
Hi @aaditya9899 I'd like to work on this issue. Could you please assign it to me?

**Comment by Prasanthisandaka2005** [comment]
Hello, @aaditya9899! ,Could you please assign me this task? I'm looking forward to make a meaningful contribution to your project.

**Comment by aaditya9899** [comment]
Sure @Vaishali785 go ahead.
@Prasanthisandaka2005 there will be more issues soon or feel free to create your own issue request you think would be suitable or could be a better feature !

**Comment by Vaishali785** [comment]
> Sure @Vaishali785 go ahead. @Prasanthisandaka2005 there will be more issues soon or feel free to create your own issue request you think would be suitable or could be a better feature !

Thanks @aaditya9899 for giving me this opportunity. But is it okay if I give my PR by October 1st evening, as I want to participate in hactoberfest.

**Comment by Vaishali785** [comment]
Hi @aaditya9899 I've given the PR, please review and merge it as soon as possible.

**Comment by aaditya9899** [comment]
can you provide a image of the changes you did here

**Comment by Vaishali785** [comment]
> can you provide a image of the changes you did here

<img width="1238" alt="Screenshot 2023-10-01 at 11 06 40 AM" src="https://github.com/aaditya9899/mini-trello/assets/81146231/8b2480a5-4779-4707-8ede-994c7d4f90f5">
