### ISSUE TITLE
Enhancing Website Responsiveness and Visual Appeal for Improved User Experience.

### ISSUE THREAD

**Issue by Prasanthisandaka2005** [aaditya9899/mini-trello#2]
Hello @aaditya9899,

I hope you are doing well. I've noticed that the Website is currently not responsive, and I'm eager to take on the task of making it not only responsive but also visually appealing to enhance the overall user experience.

Please assign this task to me. I'm excited about the opportunity to make the website great!

**Comment by aaditya9899** [comment]
Yeah sure go ahead but pls mention what changes are you looking forward to do here in brief and organized way.

**Comment by Prasanthisandaka2005** [comment]
**Make Cards Responsive:**

Implement responsive design techniques for cards.
Ensure that cards adapt to different screen sizes and orientations (e.g., mobile, tablet, desktop).

**Change Typography:**

Select a new font or typography style that aligns with the design goals.
Ensure readability and consistency across the entire project.

**Add Icons:**
Incorporate icons to enhance visual appeal and improve user experience.

Can you please assign me this under Hacktoberfest?

**Comment by aaditya9899** [comment]
Looks good to me go ahead ! 🙌

**Comment by Prasanthisandaka2005** [comment]
Hello @aaditya9899, I've made some changes. Would you please take a look and kindly share any suggestions or feedback for further refinement? Also, could you please add the 'Hacktoberfest' label?

https://github.com/aaditya9899/mini-trello/assets/122683084/c6ab6cdd-a6fa-47a1-8d4f-16623f36cf23

**Comment by aaditya9899** [comment]
looks good to me can you make a pull request so that i can review it

**Comment by Prasanthisandaka2005** [comment]
Hello @aaditya9899, I have submitted the pull request. Could you please review it?

**Comment by Prasanthisandaka2005** [comment]
> Hello @aaditya9899, I have submitted the pull request. Could you please review it?

Hello @aaditya9899, do you have any updates that need to be made?

**Comment by aaditya9899** [comment]
sorry for late reply was busy in exams , LGTM! thankx for the effort and patience.
